name = "noskrien-ziemu"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "noskrien-ziemu"
database_id = "15ae24f4-e68e-4aa3-886f-2a55ffa2e63c"
preview_database_id = "DB"  # Required for Pages local development

[dev]
port = 8787
